CREATE SCHEMA IF NOT EXISTS XFZX;
DROP TABLE IF EXISTS XFZX.T_XFZX_SW_SWDJ;
CREATE TABLE XFZX.T_XFZX_SW_SWDJ
(
  ID       VARCHAR2(50) NOT NULL,
  JBXX_ID  VARCHAR2(50),
  JTZZ_SSQ VARCHAR2(20),
  XM       VARCHAR2(20),
  BH       VARCHAR2(20),
  XM_SZM   VARCHAR2(20),
  SWDD     VARCHAR2(200),
  RJ_RQ    DATE,
  XB       CHAR(1),
  NL       NUMBER(3),
  ZXXQ_QR  DATE,
  ZXXQ_ZR  DATE,
  YX       VARCHAR2(10),
  C_BZ     VARCHAR2(1000),
  CONSTRAINT PK_T_XFZX_SW_SWDJ PRIMARY KEY (ID)
);

COMMENT ON TABLE XFZX.T_XFZX_SW_SWDJ IS '死亡管理_死亡登记';
COMMENT ON COLUMN XFZX.T_XFZX_SW_SWDJ.ID IS '主键ID';
COMMENT ON COLUMN XFZX.T_XFZX_SW_SWDJ.JBXX_ID IS '基本信息ID';
COMMENT ON COLUMN XFZX.T_XFZX_SW_SWDJ.JTZZ_SSQ IS '家庭住址省市区';
COMMENT ON COLUMN XFZX.T_XFZX_SW_SWDJ.XM IS '姓名';
COMMENT ON COLUMN XFZX.T_XFZX_SW_SWDJ.BH IS '编号';
COMMENT ON COLUMN XFZX.T_XFZX_SW_SWDJ.XM_SZM IS '姓名首字母';

COMMENT ON COLUMN XFZX.T_XFZX_SW_SWDJ.SWDD IS '死亡地点';
COMMENT ON COLUMN XFZX.T_XFZX_SW_SWDJ.RJ_RQ IS '入监日期';
COMMENT ON COLUMN XFZX.T_XFZX_SW_SWDJ.XB IS '性别';
COMMENT ON COLUMN XFZX.T_XFZX_SW_SWDJ.NL IS '年龄';
COMMENT ON COLUMN XFZX.T_XFZX_SW_SWDJ.ZXXQ_QR IS '执行刑期起日';
COMMENT ON COLUMN XFZX.T_XFZX_SW_SWDJ.ZXXQ_ZR IS '执行刑期止日';
COMMENT ON COLUMN XFZX.T_XFZX_SW_SWDJ.YX IS '余刑';
COMMENT ON COLUMN XFZX.T_XFZX_SW_SWDJ.C_BZ IS '备注';