name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout ${{github.repository}}
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
#      - name: Build with Maven
#        run: mvn -B test -B package --file pom.xml -X -DskipTest=true
#      - name: Send mail
#        uses: dawidd6/action-send-mail@master
#        with:
#          server_address: smtp.tmdaq.com
#          server_port: 465
#          username: ${{ secrets.MAIL_USERNAME }}
#          password: ${{ secrets.MAIL_PASSWORD }}
#          subject: ${{github.repository}} build result
#          # Literal body:
#          body: ${{github.repository}} build success
#          # Read file contents as body:
#          # body: file://README.md
#          to: vttmlin@tmdaq.com
#          from: GitHub Actions
#          # Optional content type:
#          content_type: text/html
#      - name: send email action
        uses: AlexisMateo/sendmail-action@5
        with:
          smtp-server: smtp.tmdaq.com
          smtp-server-port: 465
          auth-user: ${{ secrets.MAIL_USERNAME }}
          auth-password: ${{ secrets.MAIL_PASSWORD }}
          subject: ${{github.repository}} build result
          # The message to be sended
          body: ${{github.repository}} build success
          # where is the message from
          from: GitHub Actions
          # Who to send
          to: vttmlin@tmdaq.com
          # use secure connection?
          is-tls: true
          # send commit message as body
          # commit-message: # optional