name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B test -B package --file pom.xml -X
    - name: Send mail
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.tmdaq.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: ${{github.repository}} 构建结果
        # Literal body:
        body: ${{github.repository}} 构建成功
        # Read file contents as body:
        # body: file://README.md
        to: vttmlin@tmdaq.com
        from: github 构建机器人
        # Optional content type:
        content_type: text/html